config/routes.rb
Rails.application.routes.draw do
  devise_for :user1s
  devise_for :users

    # get 'students/index'
  # get 'students/show'
  # get 'students/edit'
  # get 'students/new'


  resources:students

  resources :posts


  namespace :api do
    namespace :v1 do
      resources :products, only: [:index, :show, :create, :update, :destroy]
    end
  end
  







  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user1.rb
class User1 < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < ApplicationController

  # GET ALL PRODUCTS

  def index
    products = Product.all
    render json: products, status: 200
  end


  # FOR SHOW  THE PRODUCT 

  def show
    product = Product.find_by(id: params[:id])
    if product
      render json: product, status: 200
    else
      render json: { error: "not Found" }, status: 404
    end
  end




# FOR CREATE THE PRODUCT

def create
  product = Product.new(
    name: prod_params[:name],
    brand: prod_params[:brand],
    price: prod_params[:price]
  )

  if product.save
    render json: { message: "Product created successfully", product: product }, status: 200
  else
    render json: { error: "Failed to create" }, status: 404
  end
end

# FOR UPDATE THE PRODUCT

def update
  product = Product.find_by(id: params[:id])

  if product
    if product.update(prod_params)
      render json: { message: "Product updated successfully", product: product }, status: 200
    else
      render json: { error: "Failed to update" }, status: 404
    end
  else
    render json: { error: "Not Found" }, status: 404
  end
end



    # FOR DELETE  THE PRODUCT 

  def destroy
    product = Product.find_by(id: params[:id])

    if product
      if product.destroy
        render json: { message: "Product deleted successfully" }, status: 200
      else
        render json: { error: "failed to delete" }, status: 404
      end
    else
      render json: { error: "not Found" }, status: 404
    end
  end


  private
  def prod_params
    params.require(:product).permit(:name, :brand, :price)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session, only: Proc.new { |c| c.request.format.json? }
  end
  

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  
  
  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
      
  end

  def edit
    @student = Student.find(params[:id])

  end

  def update
    @student = Student.find(params[:id])
    @student.update(studetn_params)
    redirect_to students_path
    

    
  end


  def create
    student = Student.create(studetn_params)
    redirect_to students_path
    
  end

  def new
    @student =Student.new
  end


def destroy
  @student = Student.find(params[:id])
  @student.destroy
redirect_to students_path
  
end



  private


  def studetn_params
    params.require(:student).permit(:name,:age)
  end

end

app/helpers/api/v1/products_helper.rb
module Api::V1::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyPRJ</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag 'application' %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <% if user_signed_in? %>
      Logged in As <strong> <%= current_user.email %></strong>
      <%= link_to "Edit Profile", edit_user_registration_path, :class=> 'navbar-link' %>
     <%= link_to "Logout", destroy_user_session_path, method: :delete, :class=> 'navbar-link' %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class=>'navbar-link' %>
      <%= link_to "Login", new_user_session_path, :class=>'navbar-link' %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= post.description %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

app/views/students/edit.html.erb
<h1>Update Student</h1>

<%= form_with model: @student do |f|%>
<%= f.text_field :name, placeholder: "Enter Your name "%> <br>
<%= f.text_field :age, placeholder: "Enter Your Age "%><br>
<%= f.submit%>
<%end%>

app/views/students/index.html.erb
<%
=begin%>
 <h1>Students</h1>

<ul>
  <%  @students.each do |std| %>
    <li>
      <%= link_to std.name, student_path(std) %>
    </li>
  <% end %>
</ul> 
<%
=end%>
<table>
  <% @students.each do |std| %>
    <tr>
      <td>
        <%= link_to std.name, student_path(std) %>
      </td>
      <td>
        <%= button_to 'Edit', edit_student_path(std), method: :get %>
      </td>
      <td>
        <%= button_to 'Remove', student_path(std), method: :delete, data: { confirm: "Are you sure?" } %>
      </td>
    </tr>
  <% end %>
  <%= link_to "Add new Student", new_student_path%>
</table>

app/views/students/new.html.erb
<h1>Students Create </h1>

<%= form_with model: @student do |f|%>
<%= f.text_field :name, placeholder: "Enter Your name "%> <br>
<%= f.text_field :age, placeholder: "Enter Your Age "%><br>
<%= f.submit%>
<%end%>

app/views/students/show.html.erb
<h1>Students Details </h1>
<h2>
<%= @student.name%>
</h2>
<p><%= @student.age%></p>